.TH "config/database.php" 3 "Sat May 15 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config/database.php \- Заголовочный файл с описанием настроек доступа к БД  

.SH SYNOPSIS
.br
.PP
.SS "Data Structures"

.in +1c
.ti -1c
.RI "class \fBDatabase\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Заголовочный файл с описанием настроек доступа к БД 

Данный файл содержит в себе определения основных классов, используемых в программе 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
