.TH "footer.php" 3 "Sat May 15 2021" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
footer.php \- Заголовочный файл с подвалом для сайта  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Заголовочный файл с подвалом для сайта 

Данный файл содержит в себе определения основных классов, используемых в программе 
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
